SSID = "Your WiFi SSID"
WIFI_PASSWORD = "Your WiFi Password"

ADAFRUIT_IO_USERNAME = ""
ADAFRUIT_IO_KEY = ""
ADAFRUIT_TEMPERATURE = "MQTT FEED KEY"
ADAFRUIT_LED = "MQTT FEED KEY"
ADAFRUIT_TEMPLIMIT = "MQTT FEED KEY"
ADAFRUIT_NOTIFICATION = "MQTT FEED KEY"