SSID = "YOUR WIFI SSID"
WIFI_PASSWORD = "YOUR WIFI PASSWORD"

ADAFRUIT_IO_USERNAME = "YOUR AIO USERNAME"
ADAFRUIT_IO_KEY = "YOUR AIO KEY"
ADAFRUIT_TEMPERATURE = "MQTT FEED KEY"
ADAFRUIT_LED = "MQTT FEED KEY"
ADAFRUIT_TEMPLIMIT = "MQTT FEED KEY"
ADAFRUIT_NOTIFICATION = "MQTT FEED KEY"